// Create STREAMLIT APP FIRST!

USE ROLE ACCOUNTADMIN;
USE DATABASE DEEP_RESEARCHER_DB;
USE SCHEMA PUBLIC;
USE WAREHOUSE DEEP_RESEARCHER_WH;
SHOW STREAMLITS IN SCHEMA DEEP_RESEARCHER_DB.PUBLIC;
// note the Name of the application, for me it was QJTX__RYZBJOFJF3, just replace {PUT THE NAME OF YOUR APP HERE}
DESCRIBE STREAMLIT DEEP_RESEARCHER_DB.PUBLIC.{PUT THE NAME OF YOUR APP HERE};

ALTER STREAMLIT DEEP_RESEARCHER_DB.PUBLIC.{PUT THE NAME OF YOUR APP HERE}
  SET EXTERNAL_ACCESS_INTEGRATIONS = (tavily_access_int)
  SECRETS = ('my_tavily_key' = deep_researcher_db.public.tavily_key);

//-------------------------- table with history
CREATE HYBRID TABLE history (
  research_id INT AUTOINCREMENT PRIMARY KEY,
  title VARCHAR(255),
  content VARCHAR,
  when_added TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP(),
  INDEX index_title (title)
);

