USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE WAREHOUSE DEEP_RESEARCHER_WH WITH WAREHOUSE_SIZE='x-small';
USE WAREHOUSE DEEP_RESEARCHER_WH;
CREATE DATABASE DEEP_RESEARCHER_DB;
USE DATABASE DEEP_RESEARCHER_DB;
USE SCHEMA PUBLIC;
CREATE STAGE packages ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE') DIRECTORY = (ENABLE = TRUE);

-- https://docs.snowflake.com/en/developer-guide/streamlit/additional-features#label-streamlit-external-network-access
CREATE OR REPLACE NETWORK RULE deep_researcher_rules
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('api.tavily.com');

CREATE OR REPLACE SECRET tavily_key
  TYPE = GENERIC_STRING
  SECRET_STRING = 'PUT YOUR KEY HERE';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION tavily_access_int
  ALLOWED_NETWORK_RULES = (deep_researcher_rules)
  ALLOWED_AUTHENTICATION_SECRETS = (tavily_key)
  ENABLED = TRUE;

GRANT READ ON SECRET tavily_key TO ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION tavily_access_int TO ROLE ACCOUNTADMIN;

// Create STREAMLIT APP NEXT
